#!/bin/bash

################# !!! #####################
#                                         #
#         THESE ARE LOCALLY RUN           #
#         bash run; cnt+z; disown         #
#                                         #
################  !!! #####################

#source the config parms

source CONFIG 

# first split the chromosomes up, note that this script is modified to 
# omit the exlude snps, because we only generate those after
# the align check step.

for CHR in $(seq 1 22)
do

	cd $DD
	#remove dups, maybe make this first?
	Rscript $R$app/remove_dup.R $DD $DATA

	#local split by 
	$plink --bfile $DATA --chr $CHR --make-bed --out $DATA_chr${CHR}

	#align check 1
	${shapeit} -check -B ${DD}${DATA}_chr${CHR} -M ${RD}genetic_map_chr${CHR}_combined_b37.txt --input-ref ${RD}ALL.chr${CHR}.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.nomono.haplotypes.gz ${RD}ALL.chr${CHR}.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.nomono.legend.gz ${RD}ALL.integrated_phase1_v3.20101123.snps_indels_svs.genotypes.sample --output-log neam_alignment_chr${CHR}

	#cleanup
	#rm -f neam_alignment_chr*.log
	#rm -f KIS3_AA_QC_complete_150731_chr*.*

	

	#this outputs exlude_snp_list.txt to $DD









done